CREATE TABLE IF NOT EXISTS Treno(Numero INTEGER PRIMARY KEY, Categoria TEXT NOT NULL);
CREATE TYPE TipoPdP AS ENUM ('Stazione', 'Semplice', 'Scambio');
CREATE TABLE IF NOT EXISTS PuntoDiPassaggio(ID INTEGER PRIMARY KEY, Coordinate POINT UNIQUE NOT NULL, Tipo TipoPdP NOT NULL);
CREATE TABLE IF NOT EXISTS AttraversamentoTeorico(IDTreno INTEGER NOT NULL, IDPdP INTEGER NOT NULL, Orario TIME NOT NULL,
    CONSTRAINT fk_treno FOREIGN KEY IDTreno REFERENCES Treno(Numero),
    CONSTRAINT fk_pdp FOREIGN KEY IDPdP REFERENCES PuntoDiPassaggio(ID));
CREATE TABLE IF NOT EXISTS Attraversamento(IDTreno INTEGER UNIQUE NOT NULL, IDPdP INTEGER UNIQUE NOT NULL, `Data` DATETIME NOT NULL,
    CONSTRAINT fk_treno FOREIGN KEY IDTreno REFERENCES Treno(Numero),
    CONSTRAINT fk_pdp FOREIGN KEY IDPdP REFERENCES PuntoDiPassaggio(ID));
CREATE TABLE IF NOT EXISTS PdPStazione(ID INTEGER PRIMARY KEY, IDPdP INTEGER UNIQUE NOT NULL, Nome TEXT NOT NULL, Binario TEXT NOT NULL,
    CONSTRAINT fk_pdp FOREIGN KEY IDPdP REFERENCES PuntoDiPassaggio(ID));
CREATE TYPE TipoRuolo AS ENUM ('Macchinista', 'Capotreno', 'Controllore');
CREATE TABLE IF NOT EXISTS Turno(IDPersona INTEGER NOT NULL, Ruolo TipoRuolo, IDTreno INTEGER NOT NULL, `Data` DATE NOT NULL);
CREATE TABLE IF NOT EXISTS Persona(ID INTEGER RIMARY KEY, Nome TEXT, Cognome TEXT);
CREATE TABLE IF NOT EXISTS Locomotiva(ID VARCHAR(12) PRIMARY KEY, Velocita INTEGER NOT NULL, Tensione TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Carrozza(ID VARCHAR(12) PRIMARY KEY, Classe INTEGER NOT NULL, Posti INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS Esercizio(IDConvoglio VARCHAR(12) NOT NULL, IDTreno INTEGER NOT NULL, `Data` DATETIME NOT NULL);
